import type { Metadata } from "next";
import { PageProvider } from "@/context/pagecontext";

export const metadata: Metadata = {
    title: "Next.js App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <PageProvider>{children}</PageProvider>
            </body>
        </html>
    );
}
